# Generated by Django 4.1.6 on 2023-02-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0002_car_brand_zoom_car_image_car_color_car_brand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("logo", models.ImageField(upload_to="img/about/", verbose_name="Logo")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "working_time",
                    models.CharField(max_length=255, verbose_name="Working Hours"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "last_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="video/last_video/",
                        verbose_name="Latest Video",
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("telegram", models.URLField(blank=True, verbose_name="Telegram")),
            ],
            options={
                "verbose_name": "About Company",
                "verbose_name_plural": "About Company",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("time", models.TimeField(auto_now_add=True, verbose_name="Time")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.car",
                        verbose_name="Car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-time"],
            },
        ),
    ]