# Generated by Django 4.1.6 on 2023-02-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0002_car_brand_zoom_car_image_car_color_car_brand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("logo", models.ImageField(upload_to="img/about", verbose_name="Лого")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "working_time",
                    models.CharField(max_length=255, verbose_name="Время работы"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Телефонный номер"),
                ),
                (
                    "last_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="video/last_video",
                        verbose_name="Последнее видео",
                    ),
                ),
                ("facebook", models.URLField(max_length=1024, verbose_name="Фейсбук")),
                (
                    "instagram",
                    models.URLField(max_length=1024, verbose_name="Инстаграм"),
                ),
                ("telegram", models.URLField(max_length=1024, verbose_name="Телеграм")),
            ],
            options={
                "verbose_name": "О компании",
                "verbose_name_plural": "О компании",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Телефонный номер"),
                ),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.car",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["id"],
            },
        ),
    ]
