# Generated by Django 4.1.6 on 2023-02-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drive_unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Очередь")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Привод",
                "verbose_name_plural": "Приводы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Engine_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug_name",
                    models.CharField(
                        max_length=255, verbose_name="Уникальное название"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="img/engine_type", verbose_name="Фотография"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип двигателя",
                "verbose_name_plural": "Типы двигателей",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Очередь")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("deactive", "deactive")],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комплектация",
                "verbose_name_plural": "Комплектации",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Image_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Очередь")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug_name",
                    models.CharField(
                        max_length=255, verbose_name="Уникальное название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип фотографии",
                "verbose_name_plural": "Типы фотографий",
                "ordering": ["order"],
            },
        ),
    ]
