# Generated by Django 4.1.6 on 2023-02-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriveUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Drive Unit",
                "verbose_name_plural": "Drive Units",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EngineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug_name",
                    models.CharField(
                        max_length=255, verbose_name="Unique Name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="engine_types/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Engine Type",
                "verbose_name_plural": "Engine Types",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment Packages",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ImageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug_name",
                    models.CharField(
                        max_length=255, verbose_name="Unique Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Type",
                "verbose_name_plural": "Image Types",
                "ordering": ["order"],
            },
        ),
    ]