# Generated by Django 4.1.6 on 2023-02-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_type",
            name="slug_name",
            field=models.CharField(
                choices=[
                    ("main_image", "Main Image"),
                    ("poster_image", "Poster Image"),
                ],
                max_length=255,
                verbose_name="Slug Name",
                unique=True
            ),
        ),
    ]