# Generated by Django 4.1.6 on 2023-02-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Очередь")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(upload_to="img/brands", verbose_name="Логотип"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("deactive", "deactive")],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ["order"],
            },
        ),
    ]
