# Generated by Django 4.1.6 on 2023-02-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "logo",
                    models.ImageField(upload_to="brands/logo/", verbose_name="Logo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["order"],
            },
        ),
    ]