# Generated by Django 4.1.6 on 2023-02-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("extra", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Очередь")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "manufacture_year",
                    models.IntegerField(default=20, verbose_name="Год выпуска"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                ("acceleration", models.FloatField(verbose_name="Разгон до 100 км/ч")),
                (
                    "power_reserver_from",
                    models.IntegerField(verbose_name="Запас хода от"),
                ),
                ("power_reserver_to", models.IntegerField(verbose_name="До")),
                ("length", models.IntegerField(verbose_name="Длина")),
                ("width", models.IntegerField(verbose_name="Ширина")),
                ("height", models.IntegerField(verbose_name="Высота")),
                ("num_of_places", models.IntegerField(verbose_name="Кол-во мест")),
                ("max_speed", models.IntegerField(verbose_name="Макс. скорость")),
                (
                    "battery_capacity",
                    models.FloatField(verbose_name="Емкость аккумулятора"),
                ),
                ("charging_speed", models.FloatField(verbose_name="Скорость зарядки")),
                (
                    "speed_in",
                    models.CharField(
                        choices=[("minutes", "minutes"), ("hours", "hours")],
                        max_length=255,
                        verbose_name="",
                    ),
                ),
                ("desc_1", models.TextField(max_length=150, verbose_name="Описание 1")),
                ("desc_2", models.TextField(max_length=150, verbose_name="Описание 2")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="В избранном"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("deactive", "deactive")],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Машина",
                "verbose_name_plural": "Машины",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="zoom",
            field=models.IntegerField(default=1, verbose_name="Маштаб"),
        ),
        migrations.CreateModel(
            name="Car_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Очередь")),
                (
                    "image",
                    models.ImageField(upload_to="img/cars", verbose_name="Фотография"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("deactive", "deactive")],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.car",
                        verbose_name="Машина",
                    ),
                ),
                (
                    "image_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="extra.image_type",
                        verbose_name="Тип фотографии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car_image",
                "verbose_name_plural": "Car_images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Car_color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Очередь")),
                ("color_1", models.CharField(max_length=255, verbose_name="Цвет 1")),
                ("color_2", models.CharField(max_length=255, verbose_name="Цвет 2")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("deactive", "deactive")],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.car",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет машины",
                "verbose_name_plural": "Цвета машин",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.brand",
                verbose_name="Бренд",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="drive_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="extra.drive_unit",
                verbose_name="Привод",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="extra.engine_type",
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="equipments",
            field=models.ManyToManyField(
                blank=True, to="extra.equipment", verbose_name="Комплектация"
            ),
        ),
    ]
