# Generated by Django 4.1.6 on 2023-02-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("extra", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "manufacture_year",
                    models.IntegerField(default=2020, verbose_name="Manufacture Year"),
                ),
                ("price", models.FloatField(verbose_name="Price")),
                ("acceleration", models.FloatField(verbose_name="Acceleration 0-100 km/h")),
                (
                    "power_reserver_from",
                    models.IntegerField(verbose_name="Power Reserve From"),
                ),
                ("power_reserver_to", models.IntegerField(verbose_name="To")),
                ("length", models.IntegerField(verbose_name="Length (mm)")),
                ("width", models.IntegerField(verbose_name="Width (mm)")),
                ("height", models.IntegerField(verbose_name="Height (mm)")),
                ("num_of_places", models.IntegerField(verbose_name="Seating Capacity")),

                ("max_speed", models.IntegerField(verbose_name="Max Speed (km/h)")),
                (
                    "battery_capacity",
                    models.FloatField(verbose_name="Battery Capacity (kWh)"),
                ),
                ("charging_speed", models.FloatField(verbose_name="Charging Speed")),
                (
                    "speed_unit",
                    models.CharField(
                        choices=[("minutes", "Minutes"), ("hours", "Hours")],
                        max_length=255,
                        verbose_name="Charging Time Unit",
                    ),
                ),
                ("desc_1", models.TextField(max_length=150, verbose_name="Description 1")),
                ("desc_2", models.TextField(max_length=150, verbose_name="Description 2")),

                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="date")),

            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="zoom",
            field=models.IntegerField(default=1, verbose_name="Zoom Level"),
        ),
        migrations.CreateModel(
            name="Car Image",

            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "image",
                    models.ImageField(upload_to="img/cars", verbose_name="Image"),

                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.car",
                        verbose_name="Car",
                    ),
                ),
                (
                    "image_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="extra.image_type",

                        verbose_name="Image Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Image",
                "verbose_name_plural": "Car Images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CarColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("color_1", models.CharField(max_length=255, verbose_name="Primary Color")),
                ("color_2", models.CharField(max_length=255, verbose_name="Secondary Color")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.car",
                        verbose_name="Car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Color",
                "verbose_name_plural": "Car Colors",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="drive_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="extra.drive_unit",

                verbose_name="Drive Unit",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="extra.engine_type",

                verbose_name="Engine Type",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="equipments",
            field=models.ManyToManyField(
                blank=True, to="extra.equipment", verbose_name="Equipment Packages"
            ),
        ),
    ]