# Generated by Django 4.1.6 on 2023-02-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extra", "0001_initial"),
        ("main", "0003_alter_car_image_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car_image",
            name="image_type",
        ),
        migrations.AddField(
            model_name="car_image",
            name="image_types",
            field=models.ManyToManyField(
                blank=True, to="extra.image_type", verbose_name="Image Types"
            ),
        ),
    ]
