# Generated by Django 4.1.6 on 2023-02-17 10:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_car_image_image_type_car_image_image_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_color",
            name="color_1",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=255,
                samples=None,
                verbose_name="Цвет 1",
            ),
        ),
        migrations.AlterField(
            model_name="car_color",
            name="color_2",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=255,
                samples=None,
                verbose_name="Цвет 2",
            ),
        ),
    ]
