# Generated by Django 4.1.6 on 2023-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_car_color_color_1_alter_car_color_color_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="power_reserver_to",
            field=models.IntegerField(verbose_name="Запас хода до"),
        ),
    ]
