# Generated by Django 4.1.6 on 2023-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_car_power_reserve_to'),  
    ]

    operations = [
        migrations.AlterModelOptions(
            name='CarImage', 
            options={
                'ordering': ['car', 'order'],
                'verbose_name': 'Car Photo',
                'verbose_name_plural': 'Car Photos'
            },
        ),
        migrations.AlterField(
            model_name='Brand', 
            name='zoom',
            field=models.FloatField(
                default=1.0,  
                verbose_name='Zoom Level', 
                help_text='Zoom scale factor for display purposes' 
            ),
        ),
    ]