# Generated by Django 4.1.6 on 2023-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_car_power_reserver_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_image',
            options={'ordering': ['car', 'order'], 'verbose_name': 'Фотография машины', 'verbose_name_plural': 'Фотографии машин'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='zoom',
            field=models.FloatField(default=1, verbose_name='Маштаб'),
        ),
    ]
