# Generated by Django 4.1.6 on 2023-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_car_image_options_alter_brand_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='height',
            field=models.FloatField(
                verbose_name='Height',
                help_text='Vehicle height in millimeters'
            ),
        ),
        migrations.AlterField(
            model_name='car',
            name='length',
            field=models.FloatField(
                verbose_name='Length', 
                help_text='Vehicle length in millimeters'
            ),
        ),
        migrations.AlterField(
            model_name='car',
            name='width',
            field=models.FloatField(
                verbose_name='Width',
                help_text='Vehicle width in millimeters'
            ),
        ),
    ]