# Generated by Django 4.1.6 on 2023-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_car_image_options_alter_brand_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='height',
            field=models.FloatField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='car',
            name='length',
            field=models.FloatField(verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='car',
            name='width',
            field=models.FloatField(verbose_name='Ширина'),
        ),
    ]
